// Turkish translations — all UI strings centralized here

export const tr = {
  // App
  appName: "SEO Pilot",
  appDescription: "Otomatik SEO yönetimi ve içerik optimizasyonu",

  // Sidebar
  nav: {
    pages: "Sayfalar",
    posts: "Yazılar",
    templates: "Şablonlar",
    audit: "Site Tarama",
    blogWriter: "Otomatik İçerik",
    keywordResearch: "Kelime Araştırma",
    chat: "AI Asistan",
    seo: "Kontrol Paneli",
    settings: "Ayarlar",
    tools: "Araçlar",
    content: "İçerik",
    seoSection: "SEO",
  },

  // Common
  common: {
    back: "Geri",
    save: "Kaydet",
    saving: "Kaydediliyor...",
    search: "Ara...",
    edit: "Düzenle",
    view: "Görüntüle",
    delete: "Sil",
    cancel: "İptal",
    send: "Gönder",
    close: "Kapat",
    loading: "Yükleniyor...",
    error: "Hata",
    success: "Başarılı",
    next: "İleri",
    previous: "Önceki",
    create: "Oluştur",
    generate: "Oluştur",
    generating: "Oluşturuluyor...",
    approve: "Onayla",
    reject: "Reddet",
    publish: "Yayınla",
    publishing: "Yayınlanıyor...",
    draft: "Taslak",
    noResults: "Sonuç bulunamadı",
    selected: "seçili",
  },

  // Statuses
  status: {
    publish: "Yayında",
    draft: "Taslak",
    pending: "Beklemede",
    private: "Özel",
    trash: "Çöp",
  },

  // Content List
  contentList: {
    title: "Başlık",
    status: "Durum",
    date: "Tarih",
    actions: "İşlemler",
    cloneWithAI: "AI ile Klonla",
    noItems: (type: string) => `${type} bulunamadı.`,
  },

  // Content Editor
  editor: {
    editPage: "Sayfayı Düzenle",
    editPost: "Yazıyı Düzenle",
    elementorContent: "Elementor İçeriği",
    fields: "Alanlar",
    elementor: "Elementor",
    wpEditor: "WP Editörü",
    title: "Başlık",
    statusLabel: "Durum",
    contentHtml: "İçerik (HTML)",
    excerpt: "Özet",
    preview: "Önizleme",
    savedSuccess: "Başarıyla kaydedildi!",
  },

  // Elementor Editor
  elementorEditor: {
    noWidgets: "Düzenlenebilir metin alanı bulunamadı",
    noWidgetsDesc: "Bu sayfa Elementor kullanmıyor veya düzenlenecek metin içermiyor.",
    saveToWP: "WordPress'e Kaydet",
    generateAll: "Tümünü Oluştur",
    briefPlaceholder: "İçerik konusunu veya açıklamasını girin...",
    briefRequired: "Lütfen önce bir konu veya açıklama girin",
    contentGenerated: "İçerik oluşturuldu! İnceleyip kaydedebilirsiniz.",
    noChanges: "Kaydedilecek bir değişiklik yok",
    savedWidgets: (n: number) => `${n} alan başarıyla güncellendi.`,
    textFields: (n: number) => `${n} düzenlenebilir alan`,
    unsavedChanges: (n: number) => `(${n} kaydedilmemiş değişiklik)`,
    section: "Bölüm",
    placeholder: "Yer tutucu",
    modified: "Değiştirildi",
    images: "Görseller",
    noImages: "Düzenlenebilir görsel bulunamadı",
    altText: "Alt Metin",
    generateAlt: "Alt Metin Oluştur",
    generateAllAlts: "Tüm Alt Metinleri Oluştur",
    altGenerated: "Alt metinler oluşturuldu!",
    missingAlt: "Alt metin eksik",
    searchStock: "Stok Fotoğraf Ara",
    searchPlaceholder: "Fotoğraf ara (ör. 'ofis', 'teknoloji')...",
    replaceImage: "Görseli Değiştir",
    imageCount: (n: number) => `${n} görsel`,
    stockSearch: "Stok Fotoğraf Ara",
    stockSearchPlaceholder: "Fotoğraf ara (ör. 'ofis', 'teknoloji')...",
    stockSearching: "Aranıyor...",
    stockNoResults: "Sonuç bulunamadı",
    stockSelect: "Seç",
    stockUploading: "Yükleniyor...",
    stockUploaded: "Yüklendi!",
    stockPhotographer: "Fotoğrafçı",
    stockApiKeyNeeded: "Unsplash API anahtarı gerekli",
    stockClose: "Kapat",
  },

  // Templates
  templates: {
    title: "Elementor Şablonları",
    subtitle: "Üstbilgi, altbilgi ve yeniden kullanılabilir bölümler",
    noTemplates: "Şablon bulunamadı.",
    template: "Şablon",
    type: "Tür",
    status: "Durum",
    actions: "İşlemler",
    editContent: "İçeriği Düzenle",
    hasDummyText: "Yer tutucu metin içeriyor",
    editTemplate: (id: number) => `${id} numaralı şablonu düzenle`,
    widgets: (n: number) => `${n} alan`,
  },

  // Chat
  chat: {
    title: "SEO Pilot Asistan",
    subtitle: "Sitenizi doğal dille yönetin",
    emptyTitle: "Siteniz hakkında bir soru sorun",
    emptyHint: 'Deneyin: "Son yazılarımı listele" veya "Kahve hakkında taslak oluştur"',
    pendingPlaceholder: "Yukarıdaki işlemi onaylayın veya reddedin...",
    inputPlaceholder: "Mesajınızı yazın...",
    confirmationRequired: "Onay Gerekli",
  },

  // Clone Dialog
  clone: {
    title: "Sayfayı AI ile Klonla",
    usingTemplate: (name: string) => `"${name}" şablon olarak kullanılacak`,
    newPageTitle: "Yeni Sayfa Başlığı",
    contentBrief: "İçerik Konusu / Açıklaması",
    briefPlaceholder: "Sayfanın ne hakkında olacağını açıklayın. AI, şablon yapısına ve bu açıklamaya göre içerik üretecektir.",
    creating: "Oluşturuluyor...",
    cloneAndGenerate: "Klonla ve İçerik Üret",
  },

  // AI Assistant (Editor)
  aiAssistant: {
    title: "AI Asistan",
    quickActions: "Hızlı işlemler:",
    suggestions: [
      "İçeriği daha profesyonel bir tonda yeniden yaz",
      "SEO meta açıklaması oluştur",
      "İçeriği İngilizceye çevir",
      "İçeriği daha kısa ve öz hale getir",
    ],
    inputPlaceholder: "AI'dan bu içerikle ilgili ne yapmasını istiyorsunuz?",
    changesApplied: "Değişiklikler editöre uygulandı.",
  },

  // Blog Writer / Otomatik İçerik
  blogWriter: {
    steps: {
      research: "Araştır",
      template: "Şablon Seç",
      create: "Oluştur",
    },
    step1: {
      topicPlaceholder: "Opsiyonel: konu yönü (ör. 'promosyon ürünleri', 'tabela çeşitleri')...",
      generateIdeas: "Fikir Üret",
      researching: "Araştırılıyor...",
      description: "AI sitenizi analiz eder ve SEO uyumlu içerik önerileri sunar — blog yazıları, hizmet sayfaları ve daha fazlası.",
      analyzing: "Site içeriği analiz ediliyor...",
      emptyState: "Başlamak için \"Fikir Üret\" düğmesine tıklayın",
      nextPickTemplates: "Sonraki Adım: Şablon Seç",
    },
    step2: {
      pageTitle: "Sayfa Başlığı",
      contentBrief: "İçerik Açıklaması (AI üretimi için)",
      elementorTemplate: "Elementor Şablonu",
      hasPlaceholder: "Yer tutucu metin içeriyor",
      nextCreatePages: "Sonraki Adım: Sayfaları Oluştur",
      widgets: (n: number) => `${n} alan`,
    },
    step3: {
      createFromTemplate: "Şablondan Sayfa Oluştur",
      creatingPage: "Sayfa oluşturuluyor...",
      createDescription: "Şablon düzeni ile taslak sayfa oluşturur, ardından AI ile içerik doldurmak için editörü açar.",
      pageCreated: (id: number) => `${id} numaralı sayfa oluşturuldu`,
      fillInstruction: "Konu alanını doldurup \"Tümünü Oluştur\" ile içeriği AI'a yazdırın",
      openInElementor: "Elementor ile Aç",
      pagesCreated: (created: number, total: number) => `${total} sayfadan ${created} tanesi oluşturuldu`,
    },
    contentTypes: {
      blog: "Blog Yazısı",
      service: "Hizmet Sayfası",
      landing: "Açılış Sayfası",
      about: "Hakkımızda",
      faq: "Sıkça Sorulan Sorular",
      other: "Diğer",
    },
  },

  // Content Audit (kept for reference, removed from nav)
  audit: {
    title: "İçerik Denetimi",
    subtitle: "Site genelinde içerik kalitesi ve SEO analizi",
    scanning: "Sayfalar taranıyor...",
    siteScore: "Site Sağlık Puanı",
    totalPages: "Toplam Sayfa",
    pagesWithIssues: "Sorunlu Sayfa",
    avgScore: "Ortalama Puan",
    rescan: "Yeniden Tara",
    deepScan: "Detaylı Tarama",
    filterAll: "Tümü",
    filterErrors: "Hatalar",
    filterWarnings: "Uyarılar",
    filterGood: "Sorunsuz",
    wordCount: "kelime",
    score: "Puan",
    issues: {
      placeholder: "Yer tutucu metin (Lorem ipsum) tespit edildi",
      empty_widget: "Boş metin alanı — sitede Lorem ipsum görünüyor",
      thin_content: "Yetersiz içerik (300 kelimeden az)",
      missing_meta: "Meta açıklama eksik",
      heading_h1_missing: "H1 başlığı eksik",
      heading_multiple_h1: "Birden fazla H1 başlığı var",
      heading_skipped: "Başlık seviyesi atlanmış",
      no_elementor: "Elementor verisi bulunamadı",
      missing_alt: "Görsel alt metni eksik",
      placeholder_image: "Yer tutucu görsel tespit edildi",
    },
  },

  // SEO Dashboard
  seo: {
    title: "SEO Kontrol Paneli",
    subtitle: "Otomatik sıralama takibi, performans izleme ve akıllı öneriler",
    notConfigured: "SerpBear Bağlantısı Gerekli",
    notConfiguredDesc: "SEO Kontrol Paneli'ni kullanabilmek için Ayarlar sayfasından SerpBear bağlantı bilgilerinizi girin.",
    goToSettings: "Ayarlara Git",
    domains: "Alan Adları",
    noDomains: "Henüz takip edilen bir alan adı yok. SerpBear üzerinden ekleyebilirsiniz.",
    keywords: "Anahtar Kelimeler",
    noKeywords: "Bu alan adı için takip edilen anahtar kelime yok.",
    position: "Sıra",
    change: "Değişim",
    bestPosition: "En İyi",
    device: "Cihaz",
    country: "Ülke",
    lastUpdated: "Son Güncelleme",
    refreshAll: "Tarama Başlat",
    refreshSelected: "Seçilenleri Tara",
    refreshing: "Taranıyor...",
    keywordDetail: "Anahtar Kelime Detayı",
    positionHistory: "Sıralama Geçmişi",
    backToList: "Listeye Dön",
    insights: "Akıllı Öneriler",
    insightsDesc: "Sıralama verilerinize dayalı aksiyon önerileri",
    analyzing: "Analiz ediliyor...",
    noInsights: "Henüz yeterli veri yok. Anahtar kelimeler tarandıkça öneriler burada görünecek.",
    insightTypes: {
      quick_win: "Hızlı Kazanım",
      declining: "Düşüşte",
      opportunity: "Fırsat",
      strong: "Güçlü Konum",
    },
    totalKeywords: "Takipteki Kelime",
    avgPosition: "Ort. Sıralama",
    top3: "İlk 3'te",
    top10: "İlk 10'da",
    mobile: "Mobil",
    desktop: "Masaüstü",
    selectDomain: "Alan adı seçin",
    addKeyword: "Anahtar Kelime Ekle",
    addKeywords: "Ekle",
    keywordPlaceholder: "Her satıra bir anahtar kelime yazın",
    deviceLabel: "Cihaz",
    countryLabel: "Ülke",
    adding: "Ekleniyor...",
    added: "Eklendi!",
    deleteKeyword: "Sil",
    deleteConfirm: "Bu anahtar kelimeyi takipten çıkarmak istediğinize emin misiniz?",
    deleting: "Siliniyor...",
    deleted: "Takipten çıkarıldı.",
    tags: "Etiketler",
    tagsPlaceholder: "etiket1, etiket2 (opsiyonel)",
    writeAuthRequired: "Ekleme ve silme işlemleri için Ayarlar'dan SerpBear kullanıcı adı ve şifresini girin.",
    // Tabs
    tabs: {
      overview: "Genel Bakış",
      rankings: "Sıralamalar",
      competitors: "Rakipler",
      insights: "Öneriler",
    },
    // GSC
    clicks: "Tıklama",
    impressions: "Gösterim",
    ctr: "Tıklama Oranı",
    avgPositionLabel: "Ort. Sıralama",
    topPages: "En Çok Tıklanan Sayfalar",
    topKeywords: "En Çok Aranan Kelimeler",
    performance: "Performans Grafiği",
    period7d: "Son 7 gün",
    period30d: "Son 30 gün",
    noGscData: "Arama Konsolu verisi henüz mevcut değil.",
    gscNotConnected: "Google Search Console henüz bağlanmamış. SerpBear üzerinden bağlayabilirsiniz.",
    page: "Sayfa",
    url: "Adres",
    visits: "Ziyaret",
    // Automation
    automation: {
      active: "Otomasyon Aktif",
      inactive: "Otomasyon Beklemede",
      lastScan: "Son tarama",
      nextScan: "Sonraki tarama",
      trackedKeywords: "takipteki kelime",
      autoScans: "Otomatik Tarama",
      autoScansDesc: "Anahtar kelimeleriniz düzenli olarak taranır ve sıralama değişiklikleri otomatik izlenir.",
      daily: "Günlük",
      ago: "önce",
      neverScanned: "Henüz tarama yapılmadı",
      scanNow: "Şimdi Tara",
    },
    // Competitors
    competitors: {
      title: "Rakip Analizi",
      desc: "Anahtar kelimelerinizde sizinle yarışan sitelerin karşılaştırmalı analizi",
      domain: "Rakip Site",
      commonKeywords: "Ortak Kelime",
      theirAvgPos: "Rakip Ort. Sıra",
      yourPos: "Siz",
      theirPos: "Rakip",
      serpView: "SERP Görünümü",
      noData: "Rakip verisi oluşması için anahtar kelimelerin en az bir kez taranması gerekiyor.",
      loading: "Rakip verileri analiz ediliyor...",
      topCompetitors: "En Sık Karşılaşılan Rakipler",
      perKeyword: "Kelime Bazlı Sıralama Karşılaştırması",
      track: "Takip Et",
      untrack: "Takibi Bırak",
      tracked: "Takipte",
      trackedTitle: "Takip Edilen Rakipler",
      trackHint: "— takip etmek istediğiniz rakipleri seçin",
    },
  },

  // Keyword Research
  research: {
    title: "Kelime Araştırma",
    subtitle: "Otomatik anahtar kelime keşfi ve fırsat analizi",
    seedPlaceholder: "Bir konu veya anahtar kelime girin (ör. 'ankara matbaa', 'promosyon ürünleri')...",
    generate: "Araştır",
    generating: "Araştırılıyor...",
    addToTracking: "Takibe Al",
    addedToTracking: "Takibe alındı",
    createContent: "İçerik Oluştur",
    volume: "Arama Hacmi",
    competition: "Rekabet",
    description: "Açıklama",
    contentType: "İçerik Türü",
    aiEstimate: "AI tahmini",
    noResults: "Bir konu girin ve \"Araştır\" düğmesine tıklayarak başlayın.",
    serpbearIdeas: "Google Ads Kelime Önerileri",
    serpbearIdeasDesc: "Google Ads verilerine dayalı gerçek arama hacimleri",
    noSerpbearIdeas: "Google Ads entegrasyonu henüz yapılandırılmamış veya bu alan adı için öneri üretilmemiş.",
    monthlySearches: "Aylık Arama",
    competitionLevels: {
      LOW: "Düşük",
      MEDIUM: "Orta",
      HIGH: "Yüksek",
    },
    selected: "seçili",
    bulkAddToTracking: "Seçilenleri Takibe Al",
  },

  // Settings
  settings: {
    title: "Ayarlar",
    subtitle: "Bağlantıları, API anahtarlarını ve AI davranışlarını yönetin",
    prompts: "AI Komut Şablonları",
    promptsDesc: "AI'ın içerik üretim tarzını özelleştirin",
    apiKeys: "API Anahtarları",
    save: "Kaydet",
    saved: "Kaydedildi!",
    resetToDefault: "Varsayılana Sıfırla",
    resetConfirm: "Bu şablonu varsayılan haline döndürmek istediğinize emin misiniz?",
    editableSection: "Düzenlenebilir",
    lockedSection: "Sabit (değiştirilemez)",
    chatPrompt: "Sohbet Asistanı",
    chatPromptDesc: "AI asistanının rol tanımı ve davranış kuralları",
    elementorPrompt: "Elementor İçerik Üretimi",
    elementorPromptDesc: "Sayfa içerikleri üretilirken kullanılan stil ve ton kuralları",
    altTextPrompt: "Görsel Alt Metni",
    altTextPromptDesc: "Görsel alt metinleri üretilirken uygulanan kurallar",
    contentIdeasPrompt: "İçerik Fikirleri",
    contentIdeasPromptDesc: "SEO araştırması için odak alanları ve strateji",
    role: "Rol Tanımı",
    guidelines: "Kurallar",
    contentRules: "İçerik Kuralları",
    seoGuidance: "SEO Rehberi",
    guidance: "Yönergeler",
    focusAreas: "Odak Alanları",
    ideaCount: "Fikir Sayısı",
    // Settings page section headers
    wpConnection: "WordPress Bağlantısı",
    siteUrl: "Site Adresi",
    username: "Kullanıcı Adı",
    appPassword: "Uygulama Şifresi",
    wpHelp: "WordPress Yönetim Paneli → Kullanıcılar → Profiliniz → Uygulama Şifreleri bölümünden oluşturabilirsiniz.",
    apiKeysSection: "API Anahtarları",
    geminiKey: "Gemini API Anahtarı",
    geminiHelp: "Google AI Studio'dan ücretsiz alabilirsiniz",
    unsplashKey: "Unsplash API Anahtarı",
    unsplashHelp: "Unsplash Developers'dan ücretsiz alabilirsiniz",
    serpbearSection: "SerpBear Bağlantısı",
    serpbearUrl: "SerpBear Adresi",
    serpbearApiKey: "API Anahtarı",
    serpbearUsername: "Kullanıcı Adı",
    serpbearPassword: "Şifre",
    serpbearHelp: "Adres ve API anahtarı veri okuma için, kullanıcı adı ve şifre ise kelime ekleme/silme işlemleri için gereklidir.",
    optional: "opsiyonel",
  },
} as const;
