// Turkish translations — all UI strings centralized here

export const tr = {
  // App
  appName: "WP Yönetici",
  appDescription: "AI destekli WordPress site yönetimi",

  // Sidebar
  nav: {
    pages: "Sayfalar",
    posts: "Yazılar",
    templates: "Şablonlar",
    blogWriter: "SEO İçerik",
    chat: "AI Sohbet",
    audit: "İçerik Denetimi",
    settings: "Ayarlar",
    tools: "Araçlar",
    content: "İçerik",
  },

  // Common
  common: {
    back: "Geri",
    save: "Kaydet",
    saving: "Kaydediliyor...",
    search: "Ara...",
    edit: "Düzenle",
    view: "Görüntüle",
    delete: "Sil",
    cancel: "İptal",
    send: "Gönder",
    close: "Kapat",
    loading: "Yükleniyor...",
    error: "Hata",
    success: "Başarılı",
    next: "İleri",
    previous: "Önceki",
    create: "Oluştur",
    generate: "Oluştur",
    generating: "Oluşturuluyor...",
    approve: "Onayla",
    reject: "Reddet",
    publish: "Yayınla",
    publishing: "Yayınlanıyor...",
    draft: "Taslak",
    noResults: "Sonuç bulunamadı",
    selected: "seçili",
  },

  // Statuses
  status: {
    publish: "Yayında",
    draft: "Taslak",
    pending: "Beklemede",
    private: "Özel",
    trash: "Çöp",
  },

  // Content List
  contentList: {
    title: "Başlık",
    status: "Durum",
    date: "Tarih",
    actions: "İşlemler",
    cloneWithAI: "AI ile Klonla",
    noItems: (type: string) => `${type} bulunamadı.`,
  },

  // Content Editor
  editor: {
    editPage: "Sayfa Düzenle",
    editPost: "Yazı Düzenle",
    elementorContent: "Elementor İçerik",
    fields: "Alanlar",
    elementor: "Elementor",
    wpEditor: "WP Editör",
    title: "Başlık",
    statusLabel: "Durum",
    contentHtml: "İçerik (HTML)",
    excerpt: "Özet",
    preview: "Önizleme",
    savedSuccess: "Başarıyla kaydedildi!",
  },

  // Elementor Editor
  elementorEditor: {
    noWidgets: "Metin alanı bulunamadı",
    noWidgetsDesc: "Bu sayfa Elementor kullanmıyor veya metin içeriği yok.",
    saveToWP: "WordPress'e Kaydet",
    generateAll: "Tümünü Oluştur",
    briefPlaceholder: "AI içerik oluşturma için konu/açıklama girin...",
    briefRequired: "Lütfen önce bir konu/açıklama girin",
    contentGenerated: "İçerik oluşturuldu! İnceleyip kaydedin.",
    noChanges: "Kaydedilecek değişiklik yok",
    savedWidgets: (n: number) => `Kaydedildi! ${n} alan güncellendi.`,
    textFields: (n: number) => `${n} metin alanı bulundu`,
    unsavedChanges: (n: number) => `(${n} kaydedilmemiş değişiklik)`,
    section: "Bölüm",
    placeholder: "Yer tutucu",
    modified: "Değiştirildi",
    images: "Görseller",
    noImages: "Görsel alanı bulunamadı",
    altText: "Alt Yazı",
    generateAlt: "AI Alt Yazı Oluştur",
    generateAllAlts: "Tüm Alt Yazıları Oluştur",
    altGenerated: "Alt yazılar oluşturuldu!",
    missingAlt: "Alt yazı eksik",
    searchStock: "Stok Fotoğraf Ara",
    searchPlaceholder: "Fotoğraf ara (ör. 'ofis', 'teknoloji')...",
    replaceImage: "Görseli Değiştir",
    imageCount: (n: number) => `${n} görsel bulundu`,
    stockSearch: "Stok Fotoğraf Ara",
    stockSearchPlaceholder: "Fotoğraf ara (ör. 'ofis', 'teknoloji')...",
    stockSearching: "Aranıyor...",
    stockNoResults: "Sonuç bulunamadı",
    stockSelect: "Seç",
    stockUploading: "Yükleniyor...",
    stockUploaded: "Yüklendi!",
    stockPhotographer: "Fotoğrafçı",
    stockApiKeyNeeded: "Unsplash API anahtarı gerekli",
    stockClose: "Kapat",
  },

  // Templates
  templates: {
    title: "Elementor Şablonları",
    subtitle: "Üst bilgi, alt bilgi ve yeniden kullanılabilir bölümler",
    noTemplates: "Şablon bulunamadı.",
    template: "Şablon",
    type: "Tür",
    status: "Durum",
    actions: "İşlemler",
    editContent: "İçerik Düzenle",
    hasDummyText: "Yer tutucu metin var",
    editTemplate: (id: number) => `Şablon #${id} Düzenle`,
    widgets: (n: number) => `${n} alan`,
  },

  // Chat
  chat: {
    title: "WP Yönetici Sohbet",
    subtitle: "WordPress sitenizi doğal dille yönetin",
    emptyTitle: "WordPress siteniz hakkında soru sorun",
    emptyHint: 'Deneyin: "Son yazılarımı listele" veya "Kahve hakkında taslak oluştur"',
    pendingPlaceholder: "Yukarıdaki işlemi onaylayın veya reddedin...",
    inputPlaceholder: "Mesaj yazın...",
    confirmationRequired: "Onay Gerekli",
  },

  // Clone Dialog
  clone: {
    title: "AI ile Sayfa Klonla",
    usingTemplate: (name: string) => `"${name}" şablon olarak kullanılıyor`,
    newPageTitle: "Yeni Sayfa Başlığı",
    contentBrief: "İçerik Açıklaması / Konu",
    briefPlaceholder: "Bu sayfanın ne hakkında olması gerektiğini açıklayın. AI, şablon yapısına ve bu açıklamaya göre içerik oluşturacaktır.",
    creating: "Oluşturuluyor...",
    cloneAndGenerate: "Klonla ve Oluştur",
  },

  // AI Assistant (Editor)
  aiAssistant: {
    title: "AI Asistan",
    quickActions: "Hızlı işlemler:",
    suggestions: [
      "İçeriği daha profesyonel bir tonda yeniden yaz",
      "SEO meta açıklamasını özet olarak ekle",
      "İçeriği İngilizce'ye çevir",
      "İçeriği daha kısa ve öz yap",
    ],
    inputPlaceholder: "AI'dan bu içeriği düzenlemesini isteyin...",
    changesApplied: "Değişiklikler editöre uygulandı.",
  },

  // Blog Writer / SEO Content
  blogWriter: {
    steps: {
      research: "Araştır",
      template: "Şablon",
      create: "Oluştur",
    },
    step1: {
      topicPlaceholder: "İsteğe bağlı: konu yönü (ör. 'promosyon ürünleri', 'tabela çeşitleri')...",
      generateIdeas: "Fikir Üret",
      researching: "Araştırılıyor...",
      description: "AI sitenizi analiz eder ve SEO uyumlu içerik önerir — sayfalar, blog yazıları, hizmet sayfaları ve daha fazlası",
      analyzing: "Site içeriği analiz ediliyor...",
      emptyState: "Başlamak için \"Fikir Üret\"e tıklayın",
      nextPickTemplates: "İleri: Şablon Seç",
    },
    step2: {
      pageTitle: "Sayfa Başlığı",
      contentBrief: "İçerik Açıklaması (AI oluşturma için)",
      elementorTemplate: "Elementor Şablonu",
      hasPlaceholder: "Yer tutucu metin var",
      nextCreatePages: "İleri: Sayfa Oluştur",
      widgets: (n: number) => `${n} alan`,
    },
    step3: {
      createFromTemplate: "Şablondan Sayfa Oluştur",
      creatingPage: "Sayfa oluşturuluyor...",
      createDescription: "Şablon düzeni ile taslak sayfa oluşturur, ardından AI ile içerik doldurmak için editörü açar",
      pageCreated: (id: number) => `Sayfa #${id} oluşturuldu`,
      fillInstruction: "Konu alanını doldurup \"Tümünü Oluştur\" ile AI içerik oluşturun",
      openInElementor: "Elementor'da Aç",
      pagesCreated: (created: number, total: number) => `${created} / ${total} sayfa oluşturuldu`,
    },
    contentTypes: {
      blog: "Blog",
      service: "Hizmet",
      landing: "Açılış Sayfası",
      about: "Hakkında",
      faq: "SSS",
      other: "Diğer",
    },
  },

  // Content Audit
  audit: {
    title: "İçerik Denetimi",
    subtitle: "Site genelinde içerik kalitesi ve SEO analizi",
    scanning: "Sayfalar taranıyor...",
    siteScore: "Site Sağlık Skoru",
    totalPages: "Toplam Sayfa",
    pagesWithIssues: "Sorunlu Sayfa",
    avgScore: "Ortalama Skor",
    rescan: "Yeniden Tara",
    deepScan: "Derin Tarama",
    filterAll: "Tümü",
    filterErrors: "Hatalar",
    filterWarnings: "Uyarılar",
    filterGood: "İyi",
    wordCount: "kelime",
    score: "Skor",
    issues: {
      placeholder: "Yer tutucu metin (Lorem ipsum) tespit edildi",
      empty_widget: "Boş metin alanı — sitede Lorem görünüyor",
      thin_content: "Yetersiz içerik (300 kelimeden az)",
      missing_meta: "Meta açıklama eksik",
      heading_h1_missing: "H1 başlığı eksik",
      heading_multiple_h1: "Birden fazla H1 başlığı",
      heading_skipped: "Başlık seviyesi atlandı",
      no_elementor: "Elementor verisi yok",
      missing_alt: "Görsel alt yazısı eksik",
      placeholder_image: "Yer tutucu görsel tespit edildi",
    },
  },
  // Settings
  settings: {
    title: "Ayarlar",
    subtitle: "AI prompt'larını ve uygulama ayarlarını yönetin",
    prompts: "AI Prompt'ları",
    promptsDesc: "AI'ın içerik oluşturma şeklini özelleştirin",
    apiKeys: "API Anahtarları",
    save: "Kaydet",
    saved: "Kaydedildi!",
    resetToDefault: "Varsayılana Dön",
    resetConfirm: "Bu prompt'u varsayılana döndürmek istediğinize emin misiniz?",
    editableSection: "Düzenlenebilir",
    lockedSection: "Kilitli (değiştirilemez)",
    chatPrompt: "Sohbet Asistanı",
    chatPromptDesc: "AI sohbet asistanının rolü ve davranış kuralları",
    elementorPrompt: "Elementor İçerik Oluşturma",
    elementorPromptDesc: "Sayfa içerikleri oluştururken kullanılan stil ve ton kuralları",
    altTextPrompt: "Görsel Alt Metin",
    altTextPromptDesc: "Görsel alt metinleri oluştururken kullanılan kurallar",
    contentIdeasPrompt: "İçerik Fikirleri",
    contentIdeasPromptDesc: "SEO içerik araştırması için odak alanları ve strateji",
    role: "Rol Tanımı",
    guidelines: "Kurallar",
    contentRules: "İçerik Kuralları",
    seoGuidance: "SEO Rehberi",
    guidance: "Yönergeler",
    focusAreas: "Odak Alanları",
    ideaCount: "Fikir Sayısı",
  },
} as const;
